services:
  - type: web
    name: bull-backend
    runtime: node
    plan: free
    region: oregon
    rootDir: .
    buildCommand: npm install && npx prisma generate && npx @nestjs/cli build
    startCommand: npm run production:start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: "*"

